// Golden-truth validation for es-correlation node (pandas reference).
// Each scenario feeds deterministic data through init → update and asserts state values
// against pandas.DataFrame.ewm(halflife=..., adjust=False).corr() / .cov(bias=True).
// See golden-truth-esCorrelation.py for derivation and self-verification.
import { expect } from 'chai';
import { describe, it } from 'mocha';
import { readFileSync } from 'fs';

import * as corr from '../index.js';
import { buildMsg } from './test-helpers.js';

// Golden-truth values generated by pandas.DataFrame.ewm() — see golden-truth-esCorrelation.py
const goldenTruth = JSON.parse( readFileSync( new URL( './golden-truth-esCorrelation.json', import.meta.url ), 'utf8' ) );

describe( 'Golden-truth validation (pandas reference)', function () {
    // S1: Basic positive correlation — halfLife=5, 10 samples
    it( 'S1: basic positive correlation matches pandas (correlation, covariance, r²)', function () {
        const gt = goldenTruth[ 'S1-basic-positive' ]; // see golden-truth-esCorrelation.py S1
        const x = [ 10, 12, 15, 11, 14, 13, 16, 12, 18, 10 ];
        const y = [ 20, 22, 28, 19, 25, 24, 30, 21, 35, 18 ];
        const spec = {
            nodeType: 'ES Correlation',
            name: 'gt_s1',
            from: { x: 'x', y: 'y' },
            halfLife: 5,
            minSamples: 2,
            stats: {
                correlation: { storeAs: 'r' },
                covariance: { storeAs: 'cov' },
                r2: { storeAs: 'r2' }
            }
        };
        const s = corr.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 ); // see golden-truth-esCorrelation.py S1

        corr.update( s, buildMsg( 'x', 'y', x[ 0 ], y[ 0 ] ) ); // init step
        for ( let i = 1; i < x.length; i += 1 ) {
            corr.update( s, buildMsg( 'x', 'y', x[ i ], y[ i ] ) );
            expect( s.correlation ).to.be.closeTo( gt.correlation[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S1
            expect( s.covariance ).to.be.closeTo( gt.covariance[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S1
            expect( s.r2 ).to.be.closeTo( gt.r2[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S1
        }
    } );

    // S2: Negative correlation — halfLife=3, 8 samples
    it( 'S2: negative correlation matches pandas (correlation, covariance, r²)', function () {
        const gt = goldenTruth[ 'S2-negative' ]; // see golden-truth-esCorrelation.py S2
        const x = [ 10, 8, 12, 6, 14, 4, 16, 2 ];
        const y = [ 2, 4, 1, 6, 0, 8, -1, 10 ];
        const spec = {
            nodeType: 'ES Correlation',
            name: 'gt_s2',
            from: { x: 'x', y: 'y' },
            halfLife: 3,
            minSamples: 2,
            stats: {
                correlation: { storeAs: 'r' },
                covariance: { storeAs: 'cov' },
                r2: { storeAs: 'r2' }
            }
        };
        const s = corr.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 ); // see golden-truth-esCorrelation.py S2

        corr.update( s, buildMsg( 'x', 'y', x[ 0 ], y[ 0 ] ) );
        for ( let i = 1; i < x.length; i += 1 ) {
            corr.update( s, buildMsg( 'x', 'y', x[ i ], y[ i ] ) );
            expect( s.correlation ).to.be.closeTo( gt.correlation[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S2
            expect( s.covariance ).to.be.closeTo( gt.covariance[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S2
            expect( s.r2 ).to.be.closeTo( gt.r2[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S2
        }
    } );

    // S3: Near-zero correlation (independent signals) — halfLife=10, 10 samples
    it( 'S3: near-zero correlation matches pandas (correlation, covariance)', function () {
        const gt = goldenTruth[ 'S3-near-zero' ]; // see golden-truth-esCorrelation.py S3
        const x = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ];
        const y = [ 5, 3, 7, 2, 8, 1, 6, 4, 9, 0 ];
        const spec = {
            nodeType: 'ES Correlation',
            name: 'gt_s3',
            from: { x: 'x', y: 'y' },
            halfLife: 10,
            minSamples: 2,
            stats: {
                correlation: { storeAs: 'r' },
                covariance: { storeAs: 'cov' }
            }
        };
        const s = corr.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 ); // see golden-truth-esCorrelation.py S3

        corr.update( s, buildMsg( 'x', 'y', x[ 0 ], y[ 0 ] ) );
        for ( let i = 1; i < x.length; i += 1 ) {
            corr.update( s, buildMsg( 'x', 'y', x[ i ], y[ i ] ) );
            expect( s.correlation ).to.be.closeTo( gt.correlation[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S3
            expect( s.covariance ).to.be.closeTo( gt.covariance[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S3
        }
    } );

    // S4: Fisher Z transformation — halfLife=10, 10 samples
    // Note: when fisherZT is enabled, the node clamps correlation to ±fisherZCap (0.9999)
    // before computing the Z transform. At step 1 (perfect correlation), state.correlation
    // is 0.9999 (not 1.0), but fisherZT matches the golden truth because the Python script
    // applies the same cap. Steps 2+ have r < 0.9999 so correlation matches directly.
    it( 'S4: Fisher Z transformation matches pandas (fisherZT, correlation)', function () {
        const gt = goldenTruth[ 'S4-fisher-z' ]; // see golden-truth-esCorrelation.py S4
        const x = [ 10, 20, 30, 25, 35, 15, 40, 22, 45, 28 ];
        const y = [ 12, 19, 31, 26, 33, 17, 38, 24, 43, 30 ];
        const spec = {
            nodeType: 'ES Correlation',
            name: 'gt_s4',
            from: { x: 'x', y: 'y' },
            halfLife: 10,
            minSamples: 2,
            fisherZT: true,
            stats: {
                correlation: { storeAs: 'r' },
                fisherZT: { storeAs: 'z' }
            }
        };
        const s = corr.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 ); // see golden-truth-esCorrelation.py S4

        corr.update( s, buildMsg( 'x', 'y', x[ 0 ], y[ 0 ] ) );
        for ( let i = 1; i < x.length; i += 1 ) {
            corr.update( s, buildMsg( 'x', 'y', x[ i ], y[ i ] ) );
            expect( s.fisherZT ).to.be.closeTo( gt.fisherZT[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S4
            // Step 1: r=1.0 clamped to fisherZCap (0.9999); subsequent steps match directly
            if ( i === 1 ) {
                expect( s.correlation ).to.be.closeTo( gt.fisherZCap, 1e-12 ); // see golden-truth-esCorrelation.py S4
            } else {
                expect( s.correlation ).to.be.closeTo( gt.correlation[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S4
            }
        }
    } );

    // S5: Step response — constant then decorrelation, halfLife=8, 12 samples
    it( 'S5: step response matches pandas (correlation, covariance, r²)', function () {
        const gt = goldenTruth[ 'S5-step-response' ]; // see golden-truth-esCorrelation.py S5
        const x = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 ];
        const y = [ 1, 2, 3, 4, 5, 5, 4, 3, 2, 1, 0, -1 ];
        const spec = {
            nodeType: 'ES Correlation',
            name: 'gt_s5',
            from: { x: 'x', y: 'y' },
            halfLife: 8,
            minSamples: 2,
            stats: {
                correlation: { storeAs: 'r' },
                covariance: { storeAs: 'cov' },
                r2: { storeAs: 'r2' }
            }
        };
        const s = corr.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 ); // see golden-truth-esCorrelation.py S5

        corr.update( s, buildMsg( 'x', 'y', x[ 0 ], y[ 0 ] ) );
        for ( let i = 1; i < x.length; i += 1 ) {
            corr.update( s, buildMsg( 'x', 'y', x[ i ], y[ i ] ) );
            // Steps 1-4: perfect correlation (r=1.0), clamped to fisherZCap=1 (no-op)
            expect( s.correlation ).to.be.closeTo( gt.correlation[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S5
            expect( s.covariance ).to.be.closeTo( gt.covariance[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S5
            expect( s.r2 ).to.be.closeTo( gt.r2[ i - 1 ], 1e-12 ); // see golden-truth-esCorrelation.py S5
        }
    } );
} );
