// Shared test fixtures and golden-truth data for kernel node tests.

import { readFileSync } from 'fs';

// Golden-truth values generated by numpy.convolve() — see golden-truth-kernel.py
export const goldenTruth = JSON.parse(
    readFileSync( new URL( './golden-truth-kernel.json', import.meta.url ), 'utf8' )
);

// ── Reusable spec templates ────────────────────────────────────────

export const PRESET_SPEC = {
    nodeType: 'Kernel',
    name: 'test',
    from: { x: 'value' },
    preset: 'smooth3',
    stats: { filtered: { storeAs: 'result' } }
};

export const CUSTOM_SPEC = {
    nodeType: 'Kernel',
    name: 'test',
    from: { x: 'value' },
    kernel: [ 0.25, 0.5, 0.25 ],
    stats: { filtered: { storeAs: 'result' } }
};

export const SUM3_SPEC = {
    nodeType: 'Kernel',
    name: 'test',
    from: { x: 'value' },
    kernel: [ 1, 1, 1 ],
    stats: { filtered: { storeAs: 'result' } }
};

export const SUM2_SPEC = {
    nodeType: 'Kernel',
    name: 'test',
    from: { x: 'value' },
    kernel: [ 1, 1 ],
    stats: { filtered: { storeAs: 'result' } }
};

// Factory: create a fresh copy of a spec (avoids shared mutation)
export const makeSpec = ( overrides ) => ( { ...PRESET_SPEC, ...overrides } );
