// Golden-truth validation for es-pairwise-correlation node (pandas reference).
// Each scenario feeds deterministic data through init → update and asserts
// state values against pandas.DataFrame.ewm(halflife=..., adjust=False).corr().
// See golden-truth-es-pairwise-correlation.py for derivation and self-verification.
import { expect } from 'chai';
import { describe, it } from 'mocha';
import { readFileSync } from 'fs';

import * as ecv from '../index.js';
import { isClose, msgFrom } from './test-helpers.js';

// Load golden-truth values generated by pandas — see golden-truth-es-pairwise-correlation.py
const goldenTruth = JSON.parse(
    readFileSync( new URL( './golden-truth-es-pairwise-correlation.json', import.meta.url ), 'utf8' )
);

describe( 'Golden-truth validation (pandas reference)', function () {

    // S1: Basic 2-variable positive correlation — halfLife=4, minSamples=3, 10 samples
    it( 'S1: basic 2-variable correlation matches pandas step-by-step', function () {
        const gt = goldenTruth[ 'S1-basic' ];
        const fields = gt.fields;
        const spec = {
            nodeType: 'ES Pairwise Correlation',
            name: 'gt_s1',
            from: { x: fields },
            halfLife: gt.halflife,
            minSamples: gt.minSamples,
            stats: { correlations: { storeAs: 'corr' } }
        };
        const s = ecv.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 );

        const xData = gt.data[ fields[ 0 ] ];
        const yData = gt.data[ fields[ 1 ] ];

        for ( let t = 0; t < xData.length; t += 1 ) {
            ecv.update( s, msgFrom( fields, [ xData[ t ], yData[ t ] ] ) );
            // Correlation: gated to 0 before minSamples, computed after
            expect( s.correlations[ 0 ] ).to.be.closeTo( gt.correlations[ t ], 1e-12 );
            // Means
            for ( let v = 0; v < fields.length; v += 1 ) {
                expect( s.means[ v ] ).to.be.closeTo( gt.means[ t ][ v ], 1e-12 );
            }
        }
    } );

    // S2: 3-variable mixed correlation — halfLife=5, minSamples=3, 10 samples
    it( 'S2: 3-variable mixed correlation (positive + negative) matches pandas', function () {
        const gt = goldenTruth[ 'S2-mixed' ];
        const fields = gt.fields;
        const spec = {
            nodeType: 'ES Pairwise Correlation',
            name: 'gt_s2',
            from: { x: fields },
            halfLife: gt.halflife,
            minSamples: gt.minSamples,
            stats: {
                correlations: { storeAs: 'corr' },
                covariances: { storeAs: 'cov' }
            }
        };
        const s = ecv.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 );

        const numSteps = gt.data[ fields[ 0 ] ].length;
        for ( let t = 0; t < numSteps; t += 1 ) {
            const vals = fields.map( ( f ) => gt.data[ f ][ t ] );
            ecv.update( s, msgFrom( fields, vals ) );

            // Check all 3 pair correlations
            for ( let p = 0; p < 3; p += 1 ) {
                expect( s.correlations[ p ] ).to.be.closeTo(
                    gt.correlations[ t ][ p ], 1e-12
                );
            }

            // Check covariances (node-formula, not pandas ewm.cov)
            for ( let p = 0; p < 3; p += 1 ) {
                expect( s.covariances[ p ] ).to.be.closeTo(
                    gt.covariances[ t ][ p ], 1e-12
                );
            }
        }
    } );

    // S3: Fisher Z transform verification against numpy.arctanh
    it( 'S3: Fisher Z transform matches numpy.arctanh for known values', function () {
        const gt = goldenTruth[ 'S3-fisherZ' ];

        // Test known r → fisherZ values
        const knownRs = Object.keys( gt.known_values );
        for ( let k = 0; k < knownRs.length; k += 1 ) {
            const r = parseFloat( knownRs[ k ] );
            const expectedZ = gt.known_values[ knownRs[ k ] ];
            // Fisher Z = 0.5 * ln((1+r)/(1-r))
            const computedZ = 0.5 * Math.log( ( 1 + r ) / ( 1 - r ) );
            expect( computedZ ).to.be.closeTo( expectedZ, 1e-12 );
        }

        // Round-trip: tanh(fisherZ(r)) == r
        const fz = gt.fisherZ;
        const rBack = Math.tanh( fz );
        expect( rBack ).to.be.closeTo( gt.roundtrip_r, 1e-12 );
    } );

    // S4: Warm-up gating — halfLife=3, minSamples=5, perfect linear data
    it( 'S4: warm-up gating timing is correct (correlations gated until minSamples)', function () {
        const gt = goldenTruth[ 'S4-warmup' ];
        const fields = [ 'p', 'q' ];
        const spec = {
            nodeType: 'ES Pairwise Correlation',
            name: 'gt_s4',
            from: { x: fields },
            halfLife: gt.halflife,
            minSamples: gt.minSamples,
            stats: { correlations: { storeAs: 'corr' } }
        };
        const s = ecv.init( spec );

        const pData = gt.data.p;
        const qData = gt.data.q;

        for ( let t = 0; t < pData.length; t += 1 ) {
            ecv.update( s, msgFrom( fields, [ pData[ t ], qData[ t ] ] ) );
            expect( s.correlations[ 0 ] ).to.be.closeTo( gt.correlations[ t ], 1e-12 );
        }

        // Verify gating explicitly: first minSamples-1 are 0, rest are 1.0
        // (perfect linear data → correlation = 1.0 after warm-up)
        for ( let t = 0; t < gt.minSamples - 1; t += 1 ) {
            expect( gt.correlations[ t ] ).to.equal( 0.0 );
        }
        for ( let t = gt.minSamples - 1; t < pData.length; t += 1 ) {
            expect( gt.correlations[ t ] ).to.be.closeTo( 1.0, 1e-10 );
        }
    } );

    // S5: 4-variable with positive and negative pairs — 20 steps, seeded random
    it( 'S5: 4-variable correlations match pandas step-by-step', function () {
        const gt = goldenTruth[ 'S5-four-var' ];
        const fields = gt.fields;
        const spec = {
            nodeType: 'ES Pairwise Correlation',
            name: 'gt_s5',
            from: { x: fields },
            halfLife: gt.halflife,
            minSamples: gt.minSamples,
            stats: { correlations: { storeAs: 'corr' } }
        };
        const s = ecv.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 );

        const numSteps = gt.data[ fields[ 0 ] ].length;
        for ( let t = 0; t < numSteps; t += 1 ) {
            const vals = fields.map( ( f ) => gt.data[ f ][ t ] );
            ecv.update( s, msgFrom( fields, vals ) );

            // Check all 6 pair correlations
            for ( let p = 0; p < 6; p += 1 ) {
                expect( s.correlations[ p ] ).to.be.closeTo(
                    gt.correlations[ t ][ p ], 1e-12
                );
            }
        }

        // Verify final correlations match the convenience field
        for ( let p = 0; p < 6; p += 1 ) {
            expect( s.correlations[ p ] ).to.be.closeTo(
                gt.finalCorrelations[ p ], 1e-12
            );
        }
    } );

    // S7: Covariance values match node-formula golden truth
    it( 'S7: covariance values match node-formula golden truth step-by-step', function () {
        const gt = goldenTruth[ 'S7-covariance' ];
        const fields = gt.fields;
        const spec = {
            nodeType: 'ES Pairwise Correlation',
            name: 'gt_s7',
            from: { x: fields },
            halfLife: gt.halflife,
            minSamples: 2,
            stats: {
                correlations: { storeAs: 'corr' },
                covariances: { storeAs: 'cov' }
            }
        };
        const s = ecv.init( spec );
        expect( s.alpha ).to.be.closeTo( gt.alpha, 1e-15 );

        const numSteps = gt.data[ fields[ 0 ] ].length;
        for ( let t = 0; t < numSteps; t += 1 ) {
            const vals = fields.map( ( f ) => gt.data[ f ][ t ] );
            ecv.update( s, msgFrom( fields, vals ) );

            // Check covariances at each step
            for ( let p = 0; p < 3; p += 1 ) {
                expect( s.covariances[ p ] ).to.be.closeTo(
                    gt.covariances[ t ][ p ], 1e-12
                );
            }

            // Check means at each step
            for ( let v = 0; v < fields.length; v += 1 ) {
                expect( s.means[ v ] ).to.be.closeTo(
                    gt.means[ t ][ v ], 1e-12
                );
            }
        }

        // Final correlations should match pandas
        for ( let p = 0; p < 3; p += 1 ) {
            if ( gt.pandasCorrelations[ p ] !== null ) {
                expect( s.correlations[ p ] ).to.be.closeTo(
                    gt.pandasCorrelations[ p ], 1e-10
                );
            }
        }
    } );

    // S8: Alpha derivation from half-life
    it( 'S8: alpha derivation matches golden truth for all half-lives', function () {
        const gt = goldenTruth[ 'S8-alpha' ];
        // JSON keys are "1.0", "2.0", etc. — iterate over keys directly
        const keys = Object.keys( gt.alphas );

        for ( let i = 0; i < keys.length; i += 1 ) {
            const hl = parseFloat( keys[ i ] );
            const expectedAlpha = gt.alphas[ keys[ i ] ];

            // Derive alpha using the same formula as the node
            const alpha = -Math.expm1( -( Math.LN2 / hl ) );
            expect( alpha ).to.be.closeTo( expectedAlpha, 1e-15 );

            // Verify the half-life property: (1 - alpha)^hl == 0.5
            const decay = Math.pow( 1.0 - alpha, hl );
            expect( isClose( decay, 0.5, 1e-10 ) ).to.equal( true );
        }
    } );

    // S6: NaN recovery — valid data still produces correct correlations
    it( 'S6: correlations after NaN recovery match valid-only golden truth', function () {
        const gt = goldenTruth[ 'S6-nan-recovery' ];
        const fields = [ 'x', 'y' ];
        const spec = {
            nodeType: 'ES Pairwise Correlation',
            name: 'gt_s6',
            from: { x: fields },
            halfLife: gt.halflife,
            minSamples: gt.minSamples,
            stats: { correlations: { storeAs: 'corr' } }
        };
        const s = ecv.init( spec );

        const xData = gt.validData.x;
        const yData = gt.validData.y;

        // Interleave NaN inputs between valid samples — node should skip them
        for ( let t = 0; t < xData.length; t += 1 ) {
            // Send an invalid input first (should be skipped)
            if ( t > 0 ) {
                ecv.update( s, { x: NaN, y: yData[ t ] } );
            }
            // Send valid input
            ecv.update( s, msgFrom( fields, [ xData[ t ], yData[ t ] ] ) );
            expect( s.correlations[ 0 ] ).to.be.closeTo(
                gt.correlationsAfterValidOnly[ t ], 1e-12
            );
        }
    } );
} );
