/**
 * Tests for lag node reference values — all assertions driven by
 * golden-truth-lag.json generated by pandas/numpy.
 *
 * @see golden-truth-lag.py for generation script
 * @see golden-truth-lag.json for reference data
 */

import { expect } from 'chai';
import { describe, it } from 'mocha';
import * as lag from '../index.js';
import { createMessage, goldenTruth } from './test-helpers.js';

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Asserts a stat value against a golden-truth entry.
 * null in JSON = NaN in JS.
 */
const assertStat = function ( actual, expected, tolerance ) {
    if ( expected === null ) {
        expect( Number.isNaN( actual ) ).to.equal( true );
    } else {
        expect( actual ).to.be.closeTo( expected, tolerance );
    }
};

// ── Test Suite ─────────────────────────────────────────────────────────────

describe( 'Lag Node — Reference Values (Golden Truth)', function () {
    // ════════════════════════════════════════════════════════════════════════
    // S1: Exponential Growth (lag=1)
    // ════════════════════════════════════════════════════════════════════════

    it( 'matches golden truth for exponential growth series (S1)', function () {
        const s1 = goldenTruth[ 'S1-exponential-growth' ];
        const spec = {
            nodeType: 'Lag',
            name: 'reference',
            from: { x: 'value' },
            timestamp: 'ts',
            stats: {
                delta: { storeAs: 'd' },
                ratio: { storeAs: 'r' },
                roc: { storeAs: 'c' },
                slope: { storeAs: 's' },
                logReturn: { storeAs: 'l' }
            }
        };
        const state = lag.init( spec );

        s1.values.forEach( ( v, i ) => {
            lag.update( state, createMessage( { value: v, ts: s1.times[ i ] } ) );

            assertStat( state.delta, s1.delta[ i ], 1e-9 );
            assertStat( state.ratio, s1.ratio[ i ], 1e-9 );
            assertStat( state.roc, s1.roc[ i ], 1e-9 );
            assertStat( state.slope, s1.slope[ i ], 1e-9 );
            assertStat( state.logReturn, s1.logReturn[ i ], 1e-9 );
        } );
    } );

    // ════════════════════════════════════════════════════════════════════════
    // S2: Linear Decrease (lag=1)
    // ════════════════════════════════════════════════════════════════════════

    it( 'matches golden truth for linear decrease series (S2)', function () {
        const s2 = goldenTruth[ 'S2-linear-decrease' ];
        const spec = {
            nodeType: 'Lag',
            name: 'linear',
            from: { x: 'value' },
            stats: {
                delta: { storeAs: 'd' },
                ratio: { storeAs: 'r' },
                roc: { storeAs: 'c' },
                logReturn: { storeAs: 'l' }
            }
        };
        const state = lag.init( spec );

        s2.values.forEach( ( v, i ) => {
            lag.update( state, createMessage( { value: v } ) );

            assertStat( state.delta, s2.delta[ i ], 1e-9 );
            assertStat( state.ratio, s2.ratio[ i ], 1e-9 );
            assertStat( state.roc, s2.roc[ i ], 1e-9 );
            assertStat( state.logReturn, s2.logReturn[ i ], 1e-9 );
        } );
    } );

    // ════════════════════════════════════════════════════════════════════════
    // S3: Lag=3
    // ════════════════════════════════════════════════════════════════════════

    it( 'matches golden truth with lag=3 (S3)', function () {
        const s3 = goldenTruth[ 'S3-lag3' ];
        const spec = {
            nodeType: 'Lag',
            name: 'lag3',
            from: { x: 'value' },
            timestamp: 'ts',
            lag: s3.lag,
            stats: {
                delta: { storeAs: 'd' },
                ratio: { storeAs: 'r' },
                roc: { storeAs: 'c' },
                slope: { storeAs: 's' },
                logReturn: { storeAs: 'l' }
            }
        };
        const state = lag.init( spec );

        s3.values.forEach( ( v, i ) => {
            lag.update( state, createMessage( { value: v, ts: s3.times[ i ] } ) );

            assertStat( state.delta, s3.delta[ i ], 1e-9 );
            assertStat( state.ratio, s3.ratio[ i ], 1e-9 );
            assertStat( state.roc, s3.roc[ i ], 1e-9 );
            assertStat( state.slope, s3.slope[ i ], 1e-9 );
            assertStat( state.logReturn, s3.logReturn[ i ], 1e-9 );
        } );
    } );
} );
