// Shared test fixtures and golden-truth data for lag node tests.

import { readFileSync } from 'fs';

// Golden-truth values generated by pandas/numpy — see golden-truth-lag.py
export const goldenTruth = JSON.parse(
    readFileSync( new URL( './golden-truth-lag.json', import.meta.url ), 'utf8' )
);

/**
 * Reference log return value for 10% growth.
 * Sourced from golden-truth JSON (numpy): ln(110/100).
 */
export const LOG_RETURN_10PCT = goldenTruth[ 'S8-basic-pairs' ].logReturn_100_110;

// ── Reusable spec templates ────────────────────────────────────────

export const DELTA_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    stats: { delta: { storeAs: 'diff' } }
};

export const RATIO_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    stats: { ratio: { storeAs: 'rel' } }
};

export const SLOPE_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    timestamp: 'ts',
    stats: { slope: { storeAs: 'rate' } }
};

export const LOG_RETURN_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    stats: { logReturn: { storeAs: 'lr' } }
};

export const ALL_STATS_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    timestamp: 'ts',
    stats: {
        delta: { storeAs: 'myDelta' },
        ratio: { storeAs: 'myRatio' },
        roc: { storeAs: 'myRoc' },
        slope: { storeAs: 'mySlope' },
        logReturn: { storeAs: 'myLogReturn' }
    }
};

export const CUMDELTA_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    stats: { cumDelta: { storeAs: 'cumD' } }
};

export const DELTA_CUMDELTA_SPEC = {
    nodeType: 'Lag',
    name: 'test',
    from: { x: 'value' },
    stats: {
        delta: { storeAs: 'd' },
        cumDelta: { storeAs: 'cumD' }
    }
};

// ── Message factory ────────────────────────────────────────────────

/**
 * Creates a test message with null prototype.
 * @param {Object} values - Key-value pairs for message fields
 * @returns {Object} Message object
 */
export const createMessage = function ( values ) {
    const msg = Object.create( null );
    Object.keys( values ).forEach( ( key ) => {
        msg[ key ] = values[ key ];
    } );
    return msg;
};

