// nodes/es-mean/test.js

import { expect } from 'chai';
import { readFileSync } from 'fs';
import { describe, it } from 'mocha';
import * as esMean from '../index.js';
import { getSupportedStats, getStatDescriptions, getNodeType, getCapabilities,
    getSupportedControlMethods, getDSLMetadata } from '../introspect.js';

// Golden-truth values generated by pandas.DataFrame.ewm() — see golden-truth-esMean.py
const goldenTruth = JSON.parse( readFileSync( new URL( './golden-truth-esMean.json', import.meta.url ), 'utf8' ) );

const createMessage = function ( temperature, ...other ) {
    const msg = Object.create( null );
    if ( temperature !== undefined ) {
        msg.temperature = temperature;
    }
    if ( other.length >= 1 ) {
        msg.pressure = other[ 0 ];
    }
    if ( other.length >= 2 ) {
        msg.vibration = other[ 1 ];
    }
    if ( other.length >= 3 ) {
        msg.voltage = other[ 2 ];
    }
    return msg;
};

// Convert target alpha -> half-life (for spec construction)
const halfLifeFromAlpha = function ( alpha ) {
    // halfLife = -1 / log2( 1 - alpha )
    return ( -1 ) / ( Math.log( 1 - alpha ) / Math.LN2 );
};

// Shared spec factory for tests that only need basic configuration
const makeSpec = function ( name, overrides ) {
    return {
        nodeType: 'ES Mean',
        name,
        from: { x: 'temperature' },
        stats: { mean: { storeAs: 'tempESM' } },
        ...overrides
    };
};

describe( 'esMean node (half-life based)', function () {
    describe( 'Basic functionality', function () {
        it( 'tracks sequence with halfLife = halfLifeFromAlpha(0.5)', function () {
            const state = esMean.init( makeSpec( 'fastESM', {
                halfLife: halfLifeFromAlpha( 0.5 ),
                stats: { mean: { storeAs: 'tempFast' } }
            } ) );
            const seq = [ 100, 110, 90, 100 ].map( ( v ) => createMessage( v ) );
            const expected = goldenTruth[ '§1-basic-alpha05' ].esm; // see golden-truth-esMean.py §1

            seq.forEach( ( msg, i ) => {
                esMean.update( state, msg );
                expect( state.esmValue ).to.be.closeTo( expected[ i ], 1e-12 ); // see golden-truth-esMean.py §1
            } );
        } );

        it( 'tracks sequence with halfLife = halfLifeFromAlpha(0.1)', function () {
            const state = esMean.init( makeSpec( 'slowESM', {
                halfLife: halfLifeFromAlpha( 0.1 ),
                stats: { mean: { storeAs: 'tempSlow' } }
            } ) );
            const seq = [ 100, 110, 90, 100 ].map( ( v ) => createMessage( v ) );
            const expected = goldenTruth[ '§2-basic-alpha01' ].esm; // see golden-truth-esMean.py §2

            seq.forEach( ( msg, i ) => {
                esMean.update( state, msg );
                expect( state.esmValue ).to.be.closeTo( expected[ i ], 1e-12 ); // see golden-truth-esMean.py §2
            } );
        } );
    } );

    describe( 'Defaults & init', function () {
        it( 'uses default halfLife (approx alpha 0.2) when not provided', function () {
            const state = esMean.init( makeSpec( 'defaultHL', {
                from: { x: 'pressure' },
                stats: { mean: { storeAs: 'pressureESM' } }
            } ) );
            expect( state.alpha ).to.be.closeTo( goldenTruth[ '§3-default-halflife' ].alpha, 1e-12 ); // see golden-truth-esMean.py §3
        } );
    } );

    describe( 'NaN / invalid handling', function () {
        it( 'ignores NaN/invalid and retains previous value', function () {
            const s = esMean.init( makeSpec( 'nanTest', {
                halfLife: halfLifeFromAlpha( 0.3 )
            } ) );
            const gt = goldenTruth[ '§4-nan-recovery' ]; // see golden-truth-esMean.py §4

            esMean.update( s, createMessage( 50.0 ) );
            expect( s.esmValue ).to.be.closeTo( gt.esm[ 0 ], 1e-12 ); // see golden-truth-esMean.py §4

            esMean.update( s, createMessage( 60.0 ) );
            expect( s.esmValue ).to.be.closeTo( gt.esm[ 1 ], 1e-12 ); // see golden-truth-esMean.py §4

            esMean.update( s, createMessage( NaN ) );
            expect( s.esmValue ).to.be.closeTo( gt.esm[ 1 ], 1e-12 ); // unchanged after NaN

            esMean.update( s, createMessage( 70.0 ) );
            expect( s.esmValue ).to.be.closeTo( gt.esm[ 2 ], 1e-12 ); // see golden-truth-esMean.py §4
        } );
    } );

    describe( 'Adaptive half-life', function () {
        it( 'increases effective alpha under high surprise', function () {
            const s = esMean.init( makeSpec( 'adaptiveHLTest', {
                from: { x: 'vibration' },
                halfLife: halfLifeFromAlpha( 0.2 ),
                adaptiveHalfLife: true,
                stats: { mean: { storeAs: 'vibrationESM' } }
            } ) );

            esMean.update( s, createMessage( undefined, undefined, 100 ) );
            expect( s.currentAlpha ).to.be.closeTo( s.alpha, 1e-12 );

            [ 100, 120, 80, 130, 70, 140, 60 ].forEach( ( v ) => {
                esMean.update( s, createMessage( undefined, undefined, v ) );
            } );

            expect( s.currentAlpha ).to.be.greaterThan( s.alpha );
        } );
    } );

    describe( 'Validation', function () {
        it( 'rejects invalid name', function () {
            expect( () => esMean.init( makeSpec( '123-invalid' ) ) ).to.throw();
        } );

        it( 'rejects missing from.x', function () {
            expect( () => esMean.init( makeSpec( 'missingX', {
                from: { }
            } ) ) ).to.throw();
        } );

        it( 'rejects invalid halfLife (zero)', function () {
            expect( () => esMean.init( makeSpec( 'badHL1', {
                halfLife: 0
            } ) ) ).to.throw();
        } );

        it( 'rejects invalid storeAs', function () {
            expect( () => esMean.init( makeSpec( 'badStore', {
                stats: { mean: { storeAs: 'store-as-invalid' } }
            } ) ) ).to.throw();
        } );

        it( 'rejects wrong nodeType', function () {
            expect( () => esMean.init( {
                nodeType: 'INVALID',
                name: 'wrongType',
                from: { x: 'temp' },
                stats: { mean: { storeAs: 'result' } }
            } ) ).to.throw();
        } );
    } );

    describe( 'Edge case: near pass-through', function () {
        it( 'halfLifeFromAlpha(0.999999) behaves ~like identity', function () {
            const s = esMean.init( makeSpec( 'alphaOne', {
                from: { x: 'voltage' },
                halfLife: halfLifeFromAlpha( 0.999999 ),
                stats: { mean: { storeAs: 'voltageESM' } }
            } ) );

            [ 12.0, 13.5, 11.8, 12.3 ].forEach( ( voltage ) => {
                esMean.update( s, createMessage( undefined, undefined, undefined, voltage ) );
                expect( +s.esmValue.toFixed( 4 ) ).to.equal( voltage );
            } );
        } );
    } );

    describe( 'Floating point edges', function () {
        it( 'handles tiny/large magnitudes', function () {
            const spec = makeSpec( 'fpTest', {
                halfLife: halfLifeFromAlpha( 0.1 ),
                stats: { mean: { storeAs: 'result' } }
            } );

            const gt = goldenTruth[ '§5-floating-point' ]; // see golden-truth-esMean.py §5
            const cases = [
                { values: [ 0.1, 0.2 ], expected: gt.cases[ 0 ].esm },
                { values: [ 1e-10, 2e-10 ], expected: gt.cases[ 1 ].esm },
                { values: [ 1e10, 1e10 + 100 ], expected: gt.cases[ 2 ].esm }
            ];

            cases.forEach( ( { values, expected } ) => {
                const s = esMean.init( spec );
                esMean.update( s, createMessage( values[ 0 ] ) );
                esMean.update( s, createMessage( values[ 1 ] ) );
                expect( s.esmValue ).to.be.closeTo( expected, 1e-9 ); // see golden-truth-esMean.py §5
            } );
        } );
    } );

    describe( 'Reset & publish', function () {
        it( 'resets state and re-initializes cleanly', function () {
            const s = esMean.init( makeSpec( 'resetTest', {
                halfLife: halfLifeFromAlpha( 0.3 ),
                adaptiveHalfLife: true
            } ) );

            esMean.update( s, createMessage( 100 ) );
            esMean.update( s, createMessage( 110 ) );
            esMean.update( s, createMessage( 120 ) );
            expect( s.isInitialized ).to.equal( true );
            expect( s.esmValue ).to.be.a( 'number' );

            esMean.reset( s );
            expect( s.esmValue ).to.equal( null );
            expect( s.isInitialized ).to.equal( false );
            expect( s.currentAlpha ).to.equal( s.alpha );
            expect( s.lastValue ).to.equal( null );

            esMean.update( s, createMessage( 50 ) );
            expect( s.esmValue ).to.equal( 50 );
        } );

        it( 'publishTo writes the configured storeAs', function () {
            const s = esMean.init( makeSpec( 'integration', {
                halfLife: halfLifeFromAlpha( 0.25 ),
                stats: { mean: { storeAs: 'smoothTemp' } }
            } ) );
            const seq = [ 20.0, 24.0, 22.0, 23.0 ];
            const expectedEsm = goldenTruth[ '§8-publish-sequence' ].esm; // see golden-truth-esMean.py §8

            seq.forEach( ( input, i ) => {
                esMean.update( s, createMessage( input ) );
                const out = Object.create( null );
                esMean.publishTo( s, out );
                expect( 'smoothTemp' in out ).to.equal( true );
                expect( out.smoothTemp ).to.be.closeTo( expectedEsm[ i ], 1e-12 ); // see golden-truth-esMean.py §8
            } );
        } );
    } );
} );


// Adaptive half-life — staged behavior: calm -> burst -> calm in one test
describe( 'Adaptive half-life (staged)', function () {
    it( 'calm -> burst -> calm: alpha elevates under surprise and drifts back', function () {
        const s = esMean.init( makeSpec( 'adaptiveHL_staged', {
            from: { x: 'vibration' },
            halfLife: halfLifeFromAlpha( 0.2 ),
            adaptiveHalfLife: true,
            stats: { mean: { storeAs: 'vibrationESM' } }
        } ) );
        const baseAlpha = s.alpha;

        // Calm phase: constant input
        [ 100, 100, 100, 100, 100 ].forEach( ( v ) => {
            esMean.update( s, createMessage( undefined, undefined, v ) );
        } );
        expect( s.currentAlpha ).to.be.closeTo( baseAlpha, 1e-12 );
        expect( s.esAbsInnovation ).to.not.equal( null ); // tracker engaged

        // Burst phase: high innovation
        [ 300, 90, 280, 70 ].forEach( ( v ) => {
            esMean.update( s, createMessage( undefined, undefined, v ) );
        } );
        const afterBurst = s.currentAlpha;
        expect( afterBurst ).to.be.greaterThan( baseAlpha );

        // Calm again: alpha drifts back toward base
        [ 100, 100, 100, 100, 100, 100 ].forEach( ( v ) => {
            esMean.update( s, createMessage( undefined, undefined, v ) );
        } );
        const afterCalm = s.currentAlpha;

        // Closer to base than after the burst
        expect( afterBurst - baseAlpha ).to.be.greaterThan( ( afterCalm - baseAlpha ) - 1e-12 );

        // Within +/-5% of base once calm again
        expect( afterCalm ).to.be.at.most( baseAlpha * 1.05 );
        expect( afterCalm ).to.be.at.least( baseAlpha * 0.95 );
    } );
} );

describe( 'Recompute', function () {
    it( 'returns true and leaves state unchanged', function () {
        const s = esMean.init( makeSpec( 'recomputeNoop', {
            halfLife: halfLifeFromAlpha( 0.2 ),
            stats: { mean: { storeAs: 't' } }
        } ) );
        esMean.update( s, createMessage( 10 ) );
        esMean.update( s, createMessage( 20 ) );

        const snapshot = { esmValue: s.esmValue, isInitialized: s.isInitialized, currentAlpha: s.currentAlpha };

        const ok = esMean.recompute( s );
        expect( ok ).to.equal( true );
        expect( s.esmValue ).to.equal( snapshot.esmValue );
        expect( s.isInitialized ).to.equal( snapshot.isInitialized );
        expect( s.currentAlpha ).to.equal( snapshot.currentAlpha );
    } );
} );

describe( 'Adaptive half-life edge branches', function () {
    it( 'initializes esAbsInnovation when it is null', function () {
        const s = esMean.init( makeSpec( 'absInitNullArm', {
            from: { x: 'vibration' },
            halfLife: halfLifeFromAlpha( 0.2 ),
            adaptiveHalfLife: true,
            stats: { mean: { storeAs: 'v' } }
        } ) );

        // Normal first update (sets isInitialized and abs tracker to 0)
        esMean.update( s, createMessage( undefined, undefined, 100 ) );
        expect( s.isInitialized ).to.equal( true );
        expect( s.esAbsInnovation ).to.equal( 0 );

        // Force the null arm once
        s.esAbsInnovation = null;
        esMean.update( s, createMessage( undefined, undefined, 130 ) );

        // After update, tracker should be set to |innovation|
        expect( s.esAbsInnovation ).to.be.a( 'number' );
        expect( s.esAbsInnovation ).to.be.greaterThan( 0 );
    } );

    it( 'caps currentAlpha at 0.95 when target exceeds it', function () {
        const s = esMean.init( makeSpec( 'alphaCap', {
            from: { x: 'vibration' },
            halfLife: halfLifeFromAlpha( 0.9 ),
            adaptiveHalfLife: true,
            stats: { mean: { storeAs: 'v' } }
        } ) );

        esMean.update( s, createMessage( undefined, undefined, 100 ) );
        esMean.update( s, createMessage( undefined, undefined, 10000 ) );

        // Should clamp — see golden-truth-esMean.py §7
        expect( s.currentAlpha ).to.equal( goldenTruth[ '§7-alpha-capping' ].cap );
    } );
} );

describe( 'Introspect accessors', function () {
    it( 'returns expected node type', function () {
        expect( getNodeType() ).to.equal( 'ES Mean' );
    } );

    it( 'getSupportedStats returns a copy and includes "mean"', function () {
        const a = getSupportedStats();
        expect( a ).to.be.an( 'array' );
        expect( a ).to.include( 'mean' );

        a.push( '___mutation___' );
        const b = getSupportedStats();
        expect( b ).to.not.include( '___mutation___' );
    } );

    it( 'getStatDescriptions returns a copy with string description for mean', function () {
        const d1 = getStatDescriptions();
        expect( d1 ).to.be.an( 'object' );
        expect( d1 ).to.have.property( 'mean' ).that.is.a( 'string' );

        d1.mean = '__mutated__';
        const d2 = getStatDescriptions();
        expect( d2.mean ).to.not.equal( '__mutated__' );
    } );

    it( 'getCapabilities returns a copy with description and features array', function () {
        const c1 = getCapabilities();
        expect( c1 ).to.be.an( 'object' );
        expect( c1 ).to.have.property( 'description' ).that.is.a( 'string' );
        expect( c1 ).to.have.property( 'features' ).that.is.an( 'array' ).with.length.greaterThan( 0 );

        c1.features.push( '___mutation___' );
        const c2 = getCapabilities();
        expect( c2 ).to.not.equal( c1 );
        expect( c2.features ).to.not.include( '___mutation___' );
    } );
} );

describe( 'DSL metadata', function () {
    it( 'getDSLMetadata returns specSchema, buildSpec, and crossFieldValidators', function () {
        const meta = getDSLMetadata();
        expect( meta ).to.have.property( 'specSchema' ).that.is.an( 'object' );
        expect( meta ).to.have.property( 'buildSpec' ).that.is.a( 'function' );
        expect( meta ).to.have.property( 'crossFieldValidators' ).that.is.an( 'array' );
    } );

    it( 'crossFieldValidators is an empty array', function () {
        const meta = getDSLMetadata();
        expect( meta.crossFieldValidators ).to.have.length( 0 );
    } );

    it( 'buildSpec produces a valid spec with correct fields', function () {
        const meta = getDSLMetadata();
        const spec = meta.buildSpec( 'testNode', 'temperature', { mean: { storeAs: 'result' } }, { halfLife: 5 } );

        expect( spec.nodeType ).to.equal( 'ES Mean' );
        expect( spec.name ).to.equal( 'testNode' );
        expect( spec.from.x ).to.equal( 'temperature' );
        expect( spec.stats.mean.storeAs ).to.equal( 'result' );
        expect( spec.halfLife ).to.equal( 5 );
    } );

    it( 'buildSpec output passes init without error', function () {
        const meta = getDSLMetadata();
        const spec = meta.buildSpec( 'dslInit', 'temperature', { mean: { storeAs: 'result' } }, {} );
        const state = esMean.init( spec );
        expect( state.esmValue ).to.equal( null );
        expect( state.isInitialized ).to.equal( false );
    } );
} );

describe( 'NaN handling and fault isolation', function () {

    describe( 'update with NaN input', function () {
        it( 'should set inputValidationFailed flag when x is NaN', function () {
            const state = esMean.init( makeSpec( 'nanFlag' ) );
            const result = esMean.update( state, { temperature: NaN } );

            expect( state.inputValidationFailed ).to.equal( true );
            expect( result ).to.equal( state );
        } );

        it( 'should set inputValidationFailed for Infinity', function () {
            const state = esMean.init( makeSpec( 'infFlag' ) );
            esMean.update( state, { temperature: Infinity } );
            expect( state.inputValidationFailed ).to.equal( true );
        } );

        it( 'should set inputValidationFailed for -Infinity', function () {
            const state = esMean.init( makeSpec( 'negInfFlag' ) );
            esMean.update( state, { temperature: -Infinity } );
            expect( state.inputValidationFailed ).to.equal( true );
        } );

        it( 'should set inputValidationFailed when field is undefined', function () {
            const state = esMean.init( makeSpec( 'undefFlag' ) );
            // Message lacks the 'temperature' field entirely
            const msg = Object.create( null );
            esMean.update( state, msg );
            expect( state.inputValidationFailed ).to.equal( true );
        } );

        it( 'should reset inputValidationFailed flag when valid value follows NaN', function () {
            const state = esMean.init( makeSpec( 'nanRecovery' ) );

            esMean.update( state, { temperature: NaN } );
            expect( state.inputValidationFailed ).to.equal( true );

            esMean.update( state, { temperature: 25.0 } );
            expect( state.inputValidationFailed ).to.equal( false );
        } );
    } );

    describe( 'publishTo with NaN propagation', function () {
        it( 'should propagate NaN when inputValidationFailed is true', function () {
            const state = esMean.init( makeSpec( 'nanPub', {
                stats: { mean: { storeAs: 'smoothedTemp' } }
            } ) );
            const msg = { temperature: NaN };

            esMean.update( state, msg );
            esMean.publishTo( state, msg );

            expect( Number.isNaN( msg.smoothedTemp ) ).to.equal( true );
            expect( state.inputValidationFailed ).to.equal( true );
        } );

        it( 'should not execute normal publish path when inputValidationFailed is true', function () {
            const state = esMean.init( makeSpec( 'nanPubPath', {
                stats: { mean: { storeAs: 'smoothedTemp' } }
            } ) );

            // Set up state with a valid value first
            const validMsg = { temperature: 20.0 };
            esMean.update( state, validMsg );
            esMean.publishTo( state, validMsg );
            const validValue = validMsg.smoothedTemp;

            // Now process NaN
            esMean.update( state, { temperature: NaN } );

            // State retains old value but publishes NaN
            expect( state.esmValue ).to.equal( validValue );
            const outputMsg = {};
            esMean.publishTo( state, outputMsg );
            expect( Number.isNaN( outputMsg.smoothedTemp ) ).to.equal( true );
        } );
    } );

    describe( 'complete NaN lifecycle', function () {
        it( 'should handle NaN -> valid -> NaN -> valid sequence correctly', function () {
            const state = esMean.init( makeSpec( 'nanLifecycle', {
                from: { x: 'sensor' },
                stats: { mean: { storeAs: 'filtered' } }
            } ) );
            const messages = [
                { sensor: 10 },
                { sensor: NaN },
                { sensor: 20 },
                { sensor: NaN },
                { sensor: 30 }
            ];

            const outputs = [];
            const gt = goldenTruth[ '§9-nan-lifecycle' ]; // see golden-truth-esMean.py §9

            messages.forEach( ( msg ) => {
                esMean.update( state, msg );
                const output = { ...msg };
                esMean.publishTo( state, output );
                outputs.push( output );
            } );

            expect( outputs[ 0 ].filtered ).to.be.closeTo( gt.esm[ 0 ], 1e-12 ); // see golden-truth-esMean.py §9
            expect( Number.isNaN( outputs[ 1 ].filtered ) ).to.equal( true );
            expect( outputs[ 2 ].filtered ).to.be.closeTo( gt.esm[ 1 ], 1e-12 ); // see golden-truth-esMean.py §9
            expect( Number.isNaN( outputs[ 3 ].filtered ) ).to.equal( true );
            expect( outputs[ 4 ].filtered ).to.be.closeTo( gt.esm[ 2 ], 1e-10 ); // see golden-truth-esMean.py §9
        } );
    } );

    describe( 'Field-keying support', function () {
        it( 'accepts direct halfLife value', function () {
            const state = esMean.init( makeSpec( 'fkDirect', {
                stats: { mean: { storeAs: 'avg' } },
                halfLife: 10
            } ) );
            expect( state.halfLife ).to.equal( 10 );
        } );

        it( 'uses default halfLife when not specified', function () {
            const state = esMean.init( makeSpec( 'fkDefault', {
                stats: { mean: { storeAs: 'avg' } }
            } ) );
            // see golden-truth-esMean.py §3
            expect( state.halfLife ).to.be.closeTo( goldenTruth[ '§3-default-halflife' ].halfLife, 1e-12 );
        } );

        it( 'alpha computed from halfLife', function () {
            const state = esMean.init( makeSpec( 'fkAlpha', {
                stats: { mean: { storeAs: 'avg' } },
                halfLife: 1
            } ) );
            // see golden-truth-esMean.py §1
            expect( state.alpha ).to.be.closeTo( goldenTruth[ '§1-basic-alpha05' ].alpha, 1e-12 );
        } );
    } );
} );

describe( 'Pause/Unpause control', function () {
    it( 'pause returns true and skips update', function () {
        const state = esMean.init( makeSpec( 'pauseSkip', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        const afterFirst = state.esmValue;

        expect( esMean.pause( state ) ).to.equal( true );

        esMean.update( state, createMessage( 100.0 ) );
        expect( state.esmValue ).to.equal( afterFirst );
    } );

    it( 'publishTo still runs when paused', function () {
        const state = esMean.init( makeSpec( 'pausePub', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        esMean.pause( state );

        const out = Object.create( null );
        esMean.publishTo( state, out );
        expect( 'tempESM' in out ).to.equal( true );
        expect( out.tempESM ).to.equal( state.esmValue );
    } );

    it( 'unpause returns true and resumes update', function () {
        const state = esMean.init( makeSpec( 'unpauseResume', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        esMean.pause( state );
        esMean.update( state, createMessage( 200.0 ) );
        const frozen = state.esmValue;

        expect( esMean.unpause( state ) ).to.equal( true );

        esMean.update( state, createMessage( 200.0 ) );
        expect( state.esmValue ).to.not.equal( frozen );
    } );

    it( 'double pause is safe', function () {
        const state = esMean.init( makeSpec( 'doublePause' ) );
        esMean.pause( state );
        esMean.pause( state );
        expect( state.pause ).to.equal( true );
    } );

    it( 'pause/unpause control methods declared', function () {
        const methods = getSupportedControlMethods();
        expect( methods ).to.have.property( 'pause' );
        expect( methods ).to.have.property( 'unpause' );
    } );
} );

describe( 'Disable/Enable control', function () {
    it( 'disable returns true and skips update', function () {
        const state = esMean.init( makeSpec( 'disableSkip', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        const afterFirst = state.esmValue;

        expect( esMean.disable( state ) ).to.equal( true );

        esMean.update( state, createMessage( 100.0 ) );
        expect( state.esmValue ).to.equal( afterFirst );
    } );

    it( 'publishTo skipped when disabled', function () {
        const state = esMean.init( makeSpec( 'disablePub', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        esMean.disable( state );

        const out = Object.create( null );
        esMean.publishTo( state, out );
        expect( 'tempESM' in out ).to.equal( false );
    } );

    it( 'enable returns true and resumes update', function () {
        const state = esMean.init( makeSpec( 'enableResume', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        esMean.disable( state );
        esMean.update( state, createMessage( 200.0 ) );
        const frozen = state.esmValue;

        expect( esMean.enable( state ) ).to.equal( true );

        esMean.update( state, createMessage( 200.0 ) );
        expect( state.esmValue ).to.not.equal( frozen );
    } );

    it( 'publishTo resumes after enable', function () {
        const state = esMean.init( makeSpec( 'enablePub', {
            halfLife: halfLifeFromAlpha( 0.3 )
        } ) );

        esMean.update( state, createMessage( 50.0 ) );
        esMean.disable( state );

        const out1 = Object.create( null );
        esMean.publishTo( state, out1 );
        expect( 'tempESM' in out1 ).to.equal( false );

        esMean.enable( state );

        const out2 = Object.create( null );
        esMean.publishTo( state, out2 );
        expect( 'tempESM' in out2 ).to.equal( true );
        expect( out2.tempESM ).to.equal( state.esmValue );
    } );

    it( 'double disable is safe', function () {
        const state = esMean.init( makeSpec( 'doubleDisable' ) );
        esMean.disable( state );
        esMean.disable( state );
        expect( state.disable ).to.equal( true );
    } );

    it( 'disable/enable control methods declared', function () {
        const methods = getSupportedControlMethods();
        expect( methods ).to.have.property( 'disable' );
        expect( methods ).to.have.property( 'enable' );
    } );
} );
