/**
 * @fileoverview Shared test helpers and fixtures for appraise node tests.
 */

import { readFileSync } from 'node:fs';

// ── Golden-Truth Fixture (generated by golden-truth-appraise.py) ───────────
// Decay dynamics computed via scipy.integrate.solve_ivp; definitions (MM, BLI)
// are arithmetic from their mathematical formulas.
const GOLDEN = JSON.parse(
    readFileSync( new URL( './golden-truth-fixture.json', import.meta.url ), 'utf8' )
);

// ── Test Helpers ────────────────────────────────────────────────────────────

const createMessage = function ( values ) {
    const msg = Object.create( null );
    Object.keys( values ).forEach( ( key ) => {
        msg[ key ] = values[ key ];
    } );
    return msg;
};

/**
 * Creates a minimal receptor state for unit-testing processReceptor/decayReceptor.
 */
const createReceptorState = function ( n ) {
    const s = Object.create( null );
    s.membranes = new Float64Array( n );
    s.spikes = new Float64Array( n );
    s.fired = new Uint8Array( n );
    s.charges = new Float64Array( n );
    s.rates = new Float64Array( n );
    s.VTH = 1.0;
    return s;
};

// ── Test Specs ──────────────────────────────────────────────────────────────

const MINIMAL_SPEC = {
    nodeType: 'Appraise',
    name: 'test',
    from: { x: [ 'phStat' ] },
    sources: {
        phStat: {
            deviation: 'identity',
            theta: 3,
            weight: 1.0,
            label: 'RMS shift',
            evidence: 'vibration increase'
        }
    },
    halfLife: 24,
    thresholds: {
        monitor: { at: 0.25, action: 'increase monitoring' },
        degraded: { at: 0.50, action: 'schedule inspection' },
        critical: { at: 0.75, action: 'stop equipment' }
    },
    stats: { combined: { storeAs: 'eaCombined' } }
};

const FULL_SPEC = {
    nodeType: 'Appraise',
    name: 'bearingHealth',
    from: { x: [ 'phStat', 'kurtPhStat', 'rmsTrendConf', 'esEnvelope' ] },
    sources: {
        phStat: {
            deviation: 'identity',
            theta: 3,
            weight: 1.0,
            label: 'RMS level shift',
            evidence: 'vibration energy increase'
        },
        kurtPhStat: {
            deviation: 'identity',
            theta: 2,
            weight: 1.0,
            label: 'Kurtosis level shift',
            evidence: 'impact pattern in vibration'
        },
        rmsTrendConf: {
            deviation: 'identity',
            theta: 0.5,
            weight: 0.7,
            label: 'RMS trend',
            evidence: 'sustained directional change'
        },
        esEnvelope: {
            deviation: 'identity',
            theta: 0.04,
            weight: 0.3,
            label: 'Envelope widening',
            evidence: 'new vibration modes'
        }
    },
    halfLife: 24,
    thresholds: {
        monitor: { at: 0.25, action: 'increase monitoring frequency' },
        degraded: { at: 0.50, action: 'schedule inspection within 48 hours' },
        critical: { at: 0.75, action: 'stop equipment, inspect immediately' }
    },
    stats: {
        combined: { storeAs: 'eaCombined' },
        state: { storeAs: 'eaState' },
        charge: { storeAs: 'eaCharge' },
        membrane: { storeAs: 'eaMembrane' },
        rate: { storeAs: 'eaRate' },
        calibrating: { storeAs: 'eaCalibrating' }
    }
};

const INHIBITORY_SPEC = {
    nodeType: 'Appraise',
    name: 'mixedEvidence',
    from: { x: [ 'phStat', 'trendSlope' ] },
    sources: {
        phStat: {
            deviation: 'identity',
            theta: 3,
            weight: 1.0,
            label: 'RMS shift',
            evidence: 'vibration increase'
        },
        trendSlope: {
            deviation: 'lowExceedance',
            baseline: 0,
            theta: 0.5,
            weight: -0.5,
            label: 'Falling trend',
            evidence: 'recovery'
        }
    },
    halfLife: 24,
    thresholds: {
        monitor: { at: 0.25, action: 'monitor' },
        degraded: { at: 0.50, action: 'inspect' },
        critical: { at: 0.75, action: 'stop' }
    },
    stats: { combined: { storeAs: 'combined' } }
};

const PER_SOURCE_HL_SPEC = {
    nodeType: 'Appraise',
    name: 'perSourceDecay',
    from: { x: [ 'a', 'b', 'c' ] },
    sources: {
        a: {
            deviation: 'identity',
            theta: 3,
            weight: 1.0,
            label: 'A',
            evidence: 'a',
            halfLife: 12
        },
        b: {
            deviation: 'identity',
            theta: 3,
            weight: 1.0,
            label: 'B',
            evidence: 'b'
        },
        c: {
            deviation: 'identity',
            theta: 3,
            weight: 1.0,
            label: 'C',
            evidence: 'c',
            halfLife: 48
        }
    },
    halfLife: 24,
    thresholds: {
        monitor: { at: 0.25, action: 'a' },
        degraded: { at: 0.5, action: 'b' },
        critical: { at: 0.75, action: 'c' }
    },
    stats: {
        combined: { storeAs: 'combined' },
        charge: { storeAs: 'charge' }
    }
};

// ── Computed Constants for Exact Assertions ─────────────────────────────────

const TAU = 24 / Math.LN2;
const TAU_12 = 12 / Math.LN2;
const TAU_48 = 48 / Math.LN2;

export {
    createMessage, createReceptorState,
    MINIMAL_SPEC, FULL_SPEC, INHIBITORY_SPEC, PER_SOURCE_HL_SPEC,
    TAU, TAU_12, TAU_48,
    GOLDEN
};
