// Shared test fixtures and golden-truth data for page-hinkley node tests.

import { readFileSync } from 'fs';

// Golden-truth values generated by pht_sequential + verified against
// river.drift.PageHinkley (Tier 1) and numpy vectorized (Tier 2).
// See golden-truth-page-hinkley.py for three-tier verification details.
export const goldenTruth = JSON.parse(
    readFileSync( new URL( './golden-truth-page-hinkley.json', import.meta.url ), 'utf8' )
);

// ── Reusable spec templates ────────────────────────────────────────

export const BASE_SPEC = {
    nodeType: 'Page Hinkley',
    name: 'test',
    from: { x: 'value' },
    stats: { phShift: { storeAs: 'shifted' } }
};

export const ALL_STATS_SPEC = {
    nodeType: 'Page Hinkley',
    name: 'test',
    from: { x: 'value' },
    stats: {
        phShift: { storeAs: 'shifted' },
        phTestStatistic: { storeAs: 'stat' },
        phMean: { storeAs: 'avg' }
    }
};

// Factory: create a fresh spec copy with optional overrides
export const makeSpec = ( overrides ) => ( { ...BASE_SPEC, ...overrides } );

// Factory: create a prototype-free message
export const createMessage = ( fields ) => Object.assign( Object.create( null ), fields );
