// Shared test fixtures and golden-truth data for kalman1d node tests.
//
// Golden-truth values generated by golden-truth-kalman1d.py (filterpy + scipy).
// See that script for independent reference implementation and self-verification.

import { readFileSync } from 'fs';
import * as kalman1d from '../index.js';

// ── Golden-truth data ───────────────────────────────────────────────

export const goldenTruth = JSON.parse(
    readFileSync( new URL( './golden-truth-kalman1d.json', import.meta.url ), 'utf8' )
);

// ── Tolerances ──────────────────────────────────────────────────────
// xHat, P, K: direct scalar recursion, no accumulated error
export const TOL_STATE = 1e-12;
// innovation, innovationGate: derived from state
export const TOL_DERIVED = 1e-10;

// ── Reusable spec templates ─────────────────────────────────────────

export const BASE_SPEC = {
    nodeType: 'Kalman 1d',
    name: 'kf',
    from: { x: 'temperature' },
    stats: {
        filtered: { storeAs: 'tempEst' },
        variance: { storeAs: 'tempVar' },
        innovation: { storeAs: 'tempInnov' },
        innovationGate: { storeAs: 'tempGate' }
    }
};

// Factory: create a fresh spec copy with optional overrides
export const makeSpec = ( overrides = {} ) => ( {
    ...BASE_SPEC,
    ...overrides
} );

// Factory: create a message with the configured input field
export const makeMsg = ( value, extras = {} ) => ( {
    temperature: value,
    ...extras
} );

// Feed a sequence of values through update, optionally with control
export const feedSequence = ( state, values, controlField, controlValues ) => {
    for ( let i = 0; i < values.length; i += 1 ) {
        const extras = {};
        if ( controlField && controlValues ) {
            extras[ controlField ] = controlValues[ i ];
        }
        kalman1d.update( state, makeMsg( values[ i ], extras ) );
    }
};
