// Golden-truth validation for es-stats node (pandas / invariant reference).
// Each scenario feeds deterministic data through init -> update and asserts
// state values against golden-truth-es-stats.json (generated by
// golden-truth-es-stats.py). See that script for derivation and
// self-verification.
import { expect } from 'chai';
import { describe, it } from 'mocha';

import { init, update, publishTo } from '../index.js';
import { buildMsg, loadGoldenTruth } from './test-helpers.js';

const goldenTruth = loadGoldenTruth( import.meta.url );

describe( 'Golden-truth validation (pandas / invariant reference)', function () {

    // S1: Basic EWMA mean — halfLife=5, data=[10,20,30,40,50]
    // Cross-validated against pandas.DataFrame.ewm(halflife=5, adjust=False)
    it( 'S1: EWMA mean matches pandas at each step', function () {
        const gt = goldenTruth[ 'S1-basic-ewma' ]; // see golden-truth-es-stats.py S1
        const data = [ 10, 20, 30, 40, 50 ];
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s1',
            from: { x: 'v' },
            halfLife: 5,
            stats: { mean: { storeAs: 'm' } }
        };
        const state = init( spec );
        expect( state.alpha ).to.be.closeTo( gt.alpha, 1e-15 ); // see golden-truth-es-stats.py S1

        for ( let i = 0; i < data.length; i += 1 ) {
            update( state, buildMsg( 'v', data[ i ] ) );
            expect( state.mean ).to.be.closeTo( gt.means[ i ], 1e-12 ); // see golden-truth-es-stats.py S1
        }
    } );

    // S2: Biased vs unbiased variance — halfLife=5, data=[10,20,30,40,50]
    it( 'S2: biased variance (m2) matches golden truth at each step', function () {
        const gt = goldenTruth[ 'S2-biased-unbiased' ]; // see golden-truth-es-stats.py S2
        const data = [ 10, 20, 30, 40, 50 ];
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s2b',
            from: { x: 'v' },
            halfLife: 5,
            biased: true,
            stats: {
                mean: { storeAs: 'm' },
                variance: { storeAs: 'var' },
                stdev: { storeAs: 'std' }
            }
        };
        const state = init( spec );

        for ( let i = 0; i < data.length; i += 1 ) {
            update( state, buildMsg( 'v', data[ i ] ) );
            expect( state.mean ).to.be.closeTo( gt.means[ i ], 1e-12 ); // see golden-truth-es-stats.py S2
            expect( state.m2 ).to.be.closeTo( gt.m2[ i ], 1e-12 ); // see golden-truth-es-stats.py S2
            expect( state.variance ).to.be.closeTo( gt.biasedVariance[ i ], 1e-12 ); // see golden-truth-es-stats.py S2
        }

        expect( state.variance ).to.be.closeTo( gt.finalBiasedVar, 1e-12 ); // see golden-truth-es-stats.py S2
        expect( state.stdev ).to.be.closeTo( gt.finalStdevBiased, 1e-12 ); // see golden-truth-es-stats.py S2
    } );

    it( 'S2: unbiased variance (m2/weightSum) matches golden truth at each step', function () {
        const gt = goldenTruth[ 'S2-biased-unbiased' ]; // see golden-truth-es-stats.py S2
        const data = [ 10, 20, 30, 40, 50 ];
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s2u',
            from: { x: 'v' },
            halfLife: 5,
            biased: false,
            stats: {
                mean: { storeAs: 'm' },
                variance: { storeAs: 'var' },
                stdev: { storeAs: 'std' }
            }
        };
        const state = init( spec );

        for ( let i = 0; i < data.length; i += 1 ) {
            update( state, buildMsg( 'v', data[ i ] ) );
            expect( state.weightSum ).to.be.closeTo( gt.weightSums[ i ], 1e-12 ); // see golden-truth-es-stats.py S2
            expect( state.variance ).to.be.closeTo( gt.unbiasedVariance[ i ], 1e-12 ); // see golden-truth-es-stats.py S2
        }

        expect( state.variance ).to.be.closeTo( gt.finalUnbiasedVar, 1e-12 ); // see golden-truth-es-stats.py S2
        expect( state.stdev ).to.be.closeTo( gt.finalStdevUnbiased, 1e-12 ); // see golden-truth-es-stats.py S2
    } );

    it( 'S2: unbiased variance is always >= biased variance', function () {
        const gt = goldenTruth[ 'S2-biased-unbiased' ]; // see golden-truth-es-stats.py S2

        // Skip i=0 (both are 0 for first sample)
        for ( let i = 1; i < gt.biasedVariance.length; i += 1 ) {
            expect( gt.unbiasedVariance[ i ] ).to.be.at.least( gt.biasedVariance[ i ] ); // see golden-truth-es-stats.py S2
        }
    } );

    // S3: Constant convergence — halfLife=10, value=100, n=20
    it( 'S3: constant input converges EWMA mean to constant', function () {
        const gt = goldenTruth[ 'S3-constant-convergence' ]; // see golden-truth-es-stats.py S3
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s3',
            from: { x: 'v' },
            halfLife: 10,
            stats: { mean: { storeAs: 'm' } }
        };
        const state = init( spec );

        for ( let i = 0; i < 20; i += 1 ) {
            update( state, buildMsg( 'v', 100 ) );
            expect( state.mean ).to.be.closeTo( gt.means[ i ], 1e-12 ); // see golden-truth-es-stats.py S3
        }
        expect( state.mean ).to.be.closeTo( 100.0, 1e-12 ); // see golden-truth-es-stats.py S3
    } );

    // S4: Alternating signal [10,20]*10, halfLife=10
    it( 'S4: alternating signal — means match at each step', function () {
        const gt = goldenTruth[ 'S4-alternating-signal' ]; // see golden-truth-es-stats.py S4
        const data = gt.data;
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s4m',
            from: { x: 'v' },
            halfLife: 10,
            biased: false,
            stats: {
                mean: { storeAs: 'm' },
                variance: { storeAs: 'var' },
                stdev: { storeAs: 'std' }
            }
        };
        const state = init( spec );

        for ( let i = 0; i < data.length; i += 1 ) {
            update( state, buildMsg( 'v', data[ i ] ) );
            expect( state.mean ).to.be.closeTo( gt.means[ i ], 1e-12 ); // see golden-truth-es-stats.py S4
        }
        expect( state.mean ).to.be.closeTo( gt.finalMean, 1e-12 ); // see golden-truth-es-stats.py S4
    } );

    it( 'S4: alternating signal — unbiased variance and stdev match at each step', function () {
        const gt = goldenTruth[ 'S4-alternating-signal' ]; // see golden-truth-es-stats.py S4
        const data = gt.data;
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s4v',
            from: { x: 'v' },
            halfLife: 10,
            biased: false,
            stats: {
                variance: { storeAs: 'var' },
                stdev: { storeAs: 'std' }
            }
        };
        const state = init( spec );

        for ( let i = 0; i < data.length; i += 1 ) {
            update( state, buildMsg( 'v', data[ i ] ) );
            expect( state.variance ).to.be.closeTo( gt.variancesUnbiased[ i ], 1e-12 ); // see golden-truth-es-stats.py S4
            expect( state.stdev ).to.be.closeTo( gt.stdevs[ i ], 1e-12 ); // see golden-truth-es-stats.py S4
        }
        expect( state.stdev ).to.be.closeTo( gt.finalStdev, 1e-12 ); // see golden-truth-es-stats.py S4
    } );

    it( 'S4: alternating signal — biased variance matches at each step', function () {
        const gt = goldenTruth[ 'S4-alternating-signal' ]; // see golden-truth-es-stats.py S4
        const data = gt.data;
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s4bv',
            from: { x: 'v' },
            halfLife: 10,
            biased: true,
            stats: { variance: { storeAs: 'var' } }
        };
        const state = init( spec );

        for ( let i = 0; i < data.length; i += 1 ) {
            update( state, buildMsg( 'v', data[ i ] ) );
            expect( state.variance ).to.be.closeTo( gt.variancesBiased[ i ], 1e-12 ); // see golden-truth-es-stats.py S4
        }
        expect( state.variance ).to.be.closeTo( gt.finalVarianceBiased, 1e-12 ); // see golden-truth-es-stats.py S4
    } );

    // S5: Derived metrics — baseline [100,110]*10 then anomaly
    it( 'S5: z-score for value at mean + 3*stdev equals 3.0', function () {
        const gt = goldenTruth[ 'S5-derived-metrics' ]; // see golden-truth-es-stats.py S5
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s5z',
            from: { x: 'v' },
            halfLife: 10,
            biased: false,
            stats: {
                mean: { storeAs: 'm' },
                stdev: { storeAs: 's' },
                zScore: { storeAs: 'z' }
            }
        };
        const state = init( spec );

        // Feed baseline
        gt.baselineData.forEach( function ( v ) {
            update( state, buildMsg( 'v', v ) );
        } );

        expect( state.mean ).to.be.closeTo( gt.meanAfterBaseline, 1e-12 ); // see golden-truth-es-stats.py S5
        expect( state.stdev ).to.be.closeTo( gt.stdevAfterBaseline, 1e-12 ); // see golden-truth-es-stats.py S5

        // Inject anomaly at mean + 3*stdev
        update( state, buildMsg( 'v', gt.anomalyValue ) );
        expect( state.zScore ).to.be.closeTo( gt.expectedZScore, 1e-10 ); // see golden-truth-es-stats.py S5
    } );

    it( 'S5: SNR in dB matches golden truth', function () {
        const gt = goldenTruth[ 'S5-derived-metrics' ]; // see golden-truth-es-stats.py S5
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s5snr',
            from: { x: 'v' },
            halfLife: 10,
            biased: false,
            stats: {
                mean: { storeAs: 'm' },
                snrDB: { storeAs: 'snr' }
            }
        };
        const state = init( spec );

        gt.baselineData.forEach( function ( v ) {
            update( state, buildMsg( 'v', v ) );
        } );

        expect( state.snrDB ).to.be.closeTo( gt.snrDB, 1e-10 ); // see golden-truth-es-stats.py S5
    } );

    it( 'S5: coefficient of variation matches golden truth', function () {
        const gt = goldenTruth[ 'S5-derived-metrics' ]; // see golden-truth-es-stats.py S5
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s5cv',
            from: { x: 'v' },
            halfLife: 10,
            biased: false,
            stats: {
                mean: { storeAs: 'm' },
                cv: { storeAs: 'cv' }
            }
        };
        const state = init( spec );

        gt.baselineData.forEach( function ( v ) {
            update( state, buildMsg( 'v', v ) );
        } );

        expect( state.cv ).to.be.closeTo( gt.cv, 1e-12 ); // see golden-truth-es-stats.py S5
    } );

    it( 'S5: published stats match golden truth after warmup', function () {
        const gt = goldenTruth[ 'S5-derived-metrics' ]; // see golden-truth-es-stats.py S5
        const spec = {
            nodeType: 'ES Stats',
            name: 'gt_s5pub',
            from: { x: 'v' },
            halfLife: 10,
            biased: false,
            stats: {
                mean: { storeAs: 'm' },
                stdev: { storeAs: 's' },
                snrDB: { storeAs: 'snr' },
                cv: { storeAs: 'cv' }
            }
        };
        const state = init( spec );

        gt.baselineData.forEach( function ( v ) {
            update( state, buildMsg( 'v', v ) );
        } );

        const msg = Object.create( null );
        publishTo( state, msg );

        expect( msg.m ).to.be.closeTo( gt.meanAfterBaseline, 1e-12 ); // see golden-truth-es-stats.py S5
        expect( msg.s ).to.be.closeTo( gt.stdevAfterBaseline, 1e-12 ); // see golden-truth-es-stats.py S5
        expect( msg.snr ).to.be.closeTo( gt.snrDB, 1e-10 ); // see golden-truth-es-stats.py S5
        expect( msg.cv ).to.be.closeTo( gt.cv, 1e-12 ); // see golden-truth-es-stats.py S5
    } );
} );
